# Site settings
title: Things worth sharing
email: mmacaula@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm hoping to use this blog to regularly post things I find in the course of my work 
  that I think are worth sharing, helping others avoid pitfalls.   
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michaelmac.org" # the base hostname & protocol for your site
twitter_username: mmacaula
github_username:  mmacaula

# Build settings
markdown: kramdown
